import { Agent, Task, Stage } from './types';

export const mockAgents: Agent[] = [
  {
    id: 'agent-1',
    name: 'Alex Chen',
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop',
    status: 'available',
  },
  {
    id: 'agent-2',
    name: 'Sarah Kim',
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop',
    status: 'busy',
    currentTask: 'task-3',
  },
  {
    id: 'agent-3',
    name: 'Jordan Lee',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=100&h=100&fit=crop',
    status: 'available',
  },
  {
    id: 'agent-4',
    name: 'Taylor Smith',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&h=100&fit=crop',
    status: 'offline',
  },
];

export const mockTasks: Task[] = [
  {
    id: 'task-1',
    title: 'Update landing page design',
    description: 'Redesign the landing page with new brand colors and modern layout. Focus on mobile responsiveness and accessibility.',
    stage: 'backlog',
    assignedTo: 'agent-1',
    priority: 'medium',
    createdAt: new Date('2025-01-10'),
    updatedAt: new Date('2025-01-10'),
    tags: ['design', 'frontend'],
  },
  {
    id: 'task-2',
    title: 'Fix authentication bug',
    description: 'Users are experiencing intermittent logout issues. Investigate session management and token refresh logic.',
    stage: 'todo',
    assignedTo: 'agent-2',
    priority: 'high',
    createdAt: new Date('2025-01-08'),
    updatedAt: new Date('2025-01-11'),
    tags: ['bug', 'backend', 'security'],
  },
  {
    id: 'task-3',
    title: 'Implement dark mode',
    description: 'Add dark mode support across all pages. Use CSS variables and respect system preferences.',
    stage: 'in-progress',
    assignedTo: 'agent-2',
    priority: 'medium',
    createdAt: new Date('2025-01-09'),
    updatedAt: new Date('2025-01-12'),
    tags: ['feature', 'frontend', 'ui'],
  },
  {
    id: 'task-4',
    title: 'Optimize database queries',
    description: 'Several queries are taking over 2 seconds. Add indexes and optimize N+1 query patterns.',
    stage: 'in-progress',
    assignedTo: 'agent-3',
    priority: 'high',
    createdAt: new Date('2025-01-07'),
    updatedAt: new Date('2025-01-12'),
    tags: ['performance', 'backend', 'database'],
  },
  {
    id: 'task-5',
    title: 'Code review: Payment module',
    description: 'Review the new payment integration PR. Check for security issues and test coverage.',
    stage: 'in-review',
    assignedTo: 'agent-1',
    priority: 'high',
    createdAt: new Date('2025-01-11'),
    updatedAt: new Date('2025-01-12'),
    tags: ['code-review', 'security', 'payment'],
  },
  {
    id: 'task-6',
    title: 'Write API documentation',
    description: 'Document all REST API endpoints with examples and error responses. Use OpenAPI/Swagger format.',
    stage: 'in-review',
    assignedTo: 'agent-3',
    priority: 'low',
    createdAt: new Date('2025-01-06'),
    updatedAt: new Date('2025-01-11'),
    tags: ['documentation', 'api'],
  },
  {
    id: 'task-7',
    title: 'Setup CI/CD pipeline',
    description: 'Configure GitHub Actions for automated testing and deployment to staging/production.',
    stage: 'blocked',
    assignedTo: 'agent-4',
    priority: 'medium',
    createdAt: new Date('2025-01-05'),
    updatedAt: new Date('2025-01-10'),
    blockedReason: 'Waiting for DevOps team to provision cloud infrastructure',
    tags: ['devops', 'infrastructure'],
  },
  {
    id: 'task-8',
    title: 'User onboarding flow',
    description: 'Create a step-by-step onboarding tutorial for new users with interactive tooltips.',
    stage: 'done',
    assignedTo: 'agent-1',
    priority: 'medium',
    createdAt: new Date('2025-01-03'),
    updatedAt: new Date('2025-01-09'),
    tags: ['feature', 'ux', 'frontend'],
  },
  {
    id: 'task-9',
    title: 'Mobile app icon design',
    description: 'Design app icons for iOS and Android following platform guidelines.',
    stage: 'done',
    assignedTo: 'agent-2',
    priority: 'low',
    createdAt: new Date('2025-01-02'),
    updatedAt: new Date('2025-01-08'),
    tags: ['design', 'mobile'],
  },
  {
    id: 'task-10',
    title: 'Add unit tests for auth',
    description: 'Increase test coverage for authentication module to at least 90%.',
    stage: 'todo',
    assignedTo: 'agent-3',
    priority: 'medium',
    createdAt: new Date('2025-01-11'),
    updatedAt: new Date('2025-01-11'),
    tags: ['testing', 'backend'],
  },
  {
    id: 'task-11',
    title: 'Refactor state management',
    description: 'Migrate from Redux to Zustand for simpler state management and better performance.',
    stage: 'backlog',
    assignedTo: 'agent-1',
    priority: 'low',
    createdAt: new Date('2025-01-04'),
    updatedAt: new Date('2025-01-04'),
    tags: ['refactor', 'frontend'],
  },
  {
    id: 'task-12',
    title: 'Email notification system',
    description: 'Implement transactional emails for user actions (password reset, payment confirmations, etc.).',
    stage: 'backlog',
    assignedTo: 'agent-4',
    priority: 'medium',
    createdAt: new Date('2025-01-09'),
    updatedAt: new Date('2025-01-09'),
    tags: ['feature', 'backend', 'notifications'],
  },
];

export function getTasksByStage(stage: Stage): Task[] {
  return mockTasks.filter(task => task.stage === stage);
}

export function getAgentById(id: string): Agent | undefined {
  return mockAgents.find(agent => agent.id === id);
}
