import type { Metadata } from "next";
import "./globals.css";

// Temporarily disable fonts due to network issues
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className="antialiased min-h-screen bg-background">
        <div className="relative flex min-h-screen flex-col">
          <main className="flex-1 py-6 px-6 md:px-8 lg:px-10">{children}</main>
        </div>
      </body>
    </html>
  );
}
